name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: cd 1-no-container
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.4.1
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run test
